### ISSUE TITLE
Add functions to move child left or move child right

### ISSUE THREAD

**Issue by duanecosta** [PASTAplus/metapype-eml#4]
A nice enhancement to the model code would be a pair of functions (or a single function with a "direction" parameter) to move a child node one position left or one position right relative to its sibling nodes. If the child node is already the left-most of its siblings, nothing would change on a call to move_child_left(), and of course, likewise of move_child_right() on the rightmost child.

The UI can take advantage of these functions by offering "Move Up" and "Move Down" (or up-arrow and down-arrow) buttons when displaying lists of responsible parties, coverages, etc.

**Comment by servilla** [comment]
The new function signature is the following: `def shift(self, child, direction: Shift):`

See `test_shift` in test_node.py for example usage.

**Comment by duanecosta** [comment]
In cases where there is a choice of siblings of different types, the shift should occur relative to the nearest sibling of like type. 

For example, if child_node_1 is geographicCoverage, child_node_2 is temporalCoverage, and child_node_3 is geographicCoverage, then a SHIFT LEFT operation on child_node_3 should shift it to the immediate left of child_node_1.

**Comment by servilla** [comment]
The shift to distant siblings is now in effect.
