### ISSUE TITLE
Rules should be able to represent child node choices with differing cardinalities

### ISSUE THREAD

**Issue by duanecosta** [PASTAplus/metapype-eml#5]
The current rule structure assumes that all child nodes in a choice arrangement have the same cardinality. An example of where this does not hold true are the choices under temporalCoverage: singleDateTime has cardinality 1:n, while range of dates has cardinality 1:1. There is currently no way to represent these differing cardinalities in the current rule data structure (or to process them by the rules processor).

**Comment by servilla** [comment]
Is this now a blocker (beyond what was discussed as limited subset of XML) or just documenting what is already known about the limitations of both the rule data structure and processor?

**Comment by duanecosta** [comment]
Just documenting what is already known about the limitations. In my mind the limitations can legitimately be classified as a bug though I realize you may see it differently.
