### ISSUE TITLE
JSON values should be escaped when written to file

### ISSUE THREAD

**Issue by duanecosta** [PASTAplus/metapype-eml#8]
Here's an example of text content that will invalidate the JSON when it is written to file (note the quotes around "finished"):

{"attributeDefinition":[
                                            {"id":"1e68a9f3-dbaa-11e8-b0c4-005056987be1"},
                                            {"attributes":null},
                                            {"content":"comment: if attributes are done, shouldnt the add-attributes screen have a "finished" button? (is there a finish button anywhere?)"},
                                            {"children":[null]}
                                        ]},

**Comment by servilla** [comment]
JSON is now being generated by the "JSON" system package ([63d59187d6ff94bc8d7d645d330fb61aaf988fa1](https://github.com/PASTAplus/metapype-eml/commit/63d59187d6ff94bc8d7d645d330fb61aaf988fa1)), which performs automatic escaping of reserved characters. This issue (quotes) was specifically tested in the eml2_1_1/harness.py  ([712a9e0099ea00512ab418e2b3e9ddbbcac82ff0](https://github.com/PASTAplus/metapype-eml/commit/712a9e0099ea00512ab418e2b3e9ddbbcac82ff0))
